version: '3'

services:
  bee-db:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - default

  web:
    image: jimboeri/bee-db
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8005:8000"
    depends_on:
      - bee-db
    networks:
      - default

networks:
  influxdb_default:
    external: True
  default:

volumes:
  postgres-data:
