# Generated by Django 3.1 on 2020-08-16 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beedb', '0002_auto_20200816_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colonyID', models.CharField(max_length=50)),
                ('descr', models.TextField(blank=True, null=True)),
                ('apiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beedb.apiary')),
            ],
            options={
                'ordering': ['colonyID'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='lastApiary',
            field=models.ForeignKey(blank=True, help_text='The last apiary shown on the index page', null=True, on_delete=django.db.models.deletion.SET_NULL, to='beedb.apiary'),
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('numbers', models.IntegerField(choices=[(1, 'Bees on 20 or more frames'), (2, 'Bees on 10 - 20 frames'), (3, 'bees on 4 - 9 frames'), (4, 'Bees on 3 or less frames'), (5, 'Less than a frame of bees')], help_text='How many bees in the hive', max_length=1)),
                ('colony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beedb.colony')),
            ],
        ),
    ]
