# Generated by Django 3.1.2 on 2020-12-08 04:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("beedb", "0017_auto_20201208_1713"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apiary",
            name="beekold",
        ),
    ]
