# Generated by Django 3.1.2 on 2020-12-10 01:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("beedb", "0021_auto_20201209_1644"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dt",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "outgoing",
                    models.BooleanField(
                        default=True,
                        help_text="True if colony going to another beekeeper",
                    ),
                ),
                ("beek_name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "beek_registration",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("beek_email", models.EmailField(blank=True, max_length=50, null=True)),
                ("beek_phone", models.CharField(blank=True, max_length=50, null=True)),
                ("beek_address", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "colony",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="beedb.colony",
                    ),
                ),
            ],
            options={
                "ordering": ["-dt"],
            },
        ),
        migrations.RemoveField(
            model_name="apiary",
            name="beekold1",
        ),
        migrations.DeleteModel(
            name="Beek",
        ),
    ]
