# Generated by Django 3.1.2 on 2020-12-12 23:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beedb", "0026_diary_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diary",
            name="dueDt",
            field=models.DateTimeField(),
        ),
    ]
