# Generated by Django 3.1.4 on 2021-08-15 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beedb', '0034_auto_20210815_1113'),
        ('beedb', '0030_auto_20210515_1158'),
    ]

    operations = [
    ]
