# Generated by Django 3.2.6 on 2021-10-30 02:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("beedb", "0036_merge_0035_merge_20210815_1222_0035_message"),
        ("beedb", "0036_message_html"),
    ]

    operations = []
