# Generated by Django 3.2.6 on 2021-12-05 01:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("beedb", "0037_audit_colony1"),
        ("beedb", "0037_merge_20211030_1547"),
    ]

    operations = []
