# Generated by Django 3.2.6 on 2022-01-23 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beedb', '0038_merge_0037_audit_colony1_0037_merge_20211030_1547'),
        ('beedb', '0039_auto_20220114_1651'),
    ]

    operations = [
    ]
