# Generated by Django 3.2.7 on 2022-02-12 02:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("beedb", "0040_auto_20220212_1534"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="weeklySummary",
        ),
    ]
