# Generated by Django 3.2.6 on 2022-03-26 02:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("beedb", "0047_merge_20220325_0949"),
        ("beedb", "0048_inspection_adddiary"),
    ]

    operations = []
