# Generated by Django 3.2.7 on 2022-03-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beedb", "0049_sizechoice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sizechoice",
            name="text",
            field=models.CharField(max_length=40),
        ),
    ]
