# Generated by Django 4.1.2 on 2022-10-15 21:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("beedb", "0057_auto_20220408_1655"),
        ("beedb", "0057_merge_20220408_1659"),
    ]

    operations = []
