# Generated by Django 4.1.2 on 2022-10-30 03:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("beedb", "0060_alter_treatment_insertdt_alter_treatment_postvarroa_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treatment",
            name="completed",
            field=models.BooleanField(
                default=False, verbose_name="Treatment completed & removed"
            ),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="insertDt",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name="Date treatment put in",
            ),
        ),
    ]
