# Generated by Django 4.1.3 on 2022-11-02 01:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("beedb", "0059_treatment_postvarroa_treatment_prevarroa_and_more"),
        ("beedb", "0063_rename_notes_treatment_trnotes"),
    ]

    operations = []
