# Generated by Django 4.1.2 on 2022-11-16 00:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("beedb", "0064_alter_diary_duedt"),
    ]

    operations = [
        migrations.AddField(
            model_name="audit",
            name="transfer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="beedb.transfer",
            ),
        ),
        migrations.AlterField(
            model_name="diary",
            name="dueDt",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 11, 23, 0, 21, 39, 889925, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date to complete by",
            ),
        ),
    ]
