# Generated by Django 4.1.3 on 2022-11-20 17:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beedb', '0065_audit_transfer_alter_diary_duedt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiary',
            name='latitude',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='apiary',
            name='longitude',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='diary',
            name='dueDt',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 27, 17, 43, 34, 342234, tzinfo=datetime.timezone.utc), verbose_name='Date to complete by'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='images/')),
                ('uploadDt', models.DateTimeField(default=django.utils.timezone.now)),
                ('apiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beedb.apiary')),
                ('beek', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('colony', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beedb.colony')),
                ('inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beedb.inspection')),
            ],
            options={
                'ordering': ['-uploadDt'],
            },
        ),
    ]
