# Generated by Django 4.1.3 on 2022-11-16 03:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("beedb", "0065_audit_transfer_alter_diary_duedt"),
        ("beedb", "0066_alter_diary_duedt"),
    ]

    operations = []
