# Generated by Django 4.1.7 on 2023-02-14 22:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("beedb", "0067_picture_alter_diary_duedt_delete_image"),
        ("beedb", "0068_alter_diary_duedt"),
    ]

    operations = []
