# Generated by Django 5.0.7 on 2024-07-27 01:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beedb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='dueDt',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 3, 1, 49, 15, 379839, tzinfo=datetime.timezone.utc), verbose_name='Date to complete by'),
        ),
    ]
