# Generated by Django 3.1 on 2020-08-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beedb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiary',
            options={'ordering': ['apiaryID']},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='reportType',
        ),
        migrations.AddField(
            model_name='profile',
            name='bkRegistration',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
