# Generated by Django 5.2 on 2025-10-27 03:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beedb", "0005_inspection_broodframes_alter_diary_duedt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diary",
            name="dueDt",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 3, 3, 29, 58, 645409, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date to complete by",
            ),
        ),
        migrations.AlterField(
            model_name="inspection",
            name="broodFrames",
            field=models.IntegerField(
                default=0, help_text="Number of frames with brood"
            ),
        ),
    ]
