# Generated by Django 5.2 on 2026-05-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beedb", "0006_alter_diary_duedt_alter_inspection_broodframes"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="message",
            name="lastTryDt",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
