# Generated by Django 5.2 on 2026-05-20 02:33

import beedb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beedb', '0007_message_attempts_lasttrydt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='dueDt',
            field=models.DateTimeField(default=beedb.models._diary_default_due_dt, verbose_name='Date to complete by'),
        ),
    ]
