# Generated by Django 3.1.2 on 2020-12-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beedb", "0010_auto_20201205_1241"),
    ]

    operations = [
        migrations.AddField(
            model_name="colony",
            name="status",
            field=models.CharField(
                choices=[("C", "Current"), ("D", "Dead"), ("A", "Absconded")],
                default="C",
                help_text="Current status of hive)",
                max_length=1,
            ),
        ),
    ]
