# Generated by Django 3.1.2 on 2020-12-10 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beedb', '0022_auto_20201210_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='transaction',
            field=models.IntegerField(default=0, help_text='1 - Sold'),
        ),
        migrations.AlterField(
            model_name='colony',
            name='status',
            field=models.CharField(choices=[('C', 'Current'), ('D', 'Dead'), ('A', 'Absconded'), ('S', 'Sold/given')], default='C', help_text='Current status of hive)', max_length=1),
        ),
    ]
