# Generated by Django 3.1.2 on 2020-12-13 04:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("beedb", "0027_auto_20201213_1230"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="diary",
            options={"ordering": ["-dueDt"]},
        ),
    ]
