# Generated by Django 3.2.6 on 2021-08-14 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beedb', '0032_colony_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='colony',
            name='lastAction',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colony',
            name='status_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
