# Generated by Django 3.2.6 on 2021-08-14 23:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("beedb", "0033_auto_20210815_1051"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colony",
            name="lastAction",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="colony",
            name="status_dt",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
