# Generated by Django 3.2.6 on 2021-08-19 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beedb', '0035_merge_20210815_1222'),
        ('beedb', '0035_message'),
    ]

    operations = [
    ]
