# Generated by Django 3.2.6 on 2022-01-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beedb', '0040_merge_20220123_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='inspectPeriodSummer',
            field=models.IntegerField(default=14, verbose_name='Days between inspections in summer'),
        ),
    ]
