# Generated by Django 3.2.7 on 2022-02-14 01:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beedb", "0041_remove_profile_weeklysummary"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="commsLstWeeklyEmail",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
