# Generated by Django 3.2.6 on 2022-02-15 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beedb', '0041_alter_profile_inspectperiodsummer'),
        ('beedb', '0042_profile_commslstweeklyemail'),
    ]

    operations = [
    ]
