# Generated by Django 3.2.7 on 2022-03-23 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beedb', '0045_alter_feedback_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('organic', models.BooleanField(default=False)),
                ('requireRemoval', models.BooleanField(default=False)),
                ('daysInHive', models.IntegerField()),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('instructions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('insertDt', models.DateTimeField(blank=True, null=True)),
                ('removeDt', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField()),
                ('colony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beedb.colony')),
                ('inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beedb.inspection')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beedb.treatmenttype')),
            ],
        ),
    ]
