# Generated by Django 3.2.7 on 2022-04-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beedb', '0050_alter_sizechoice_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colony',
            name='size',
            field=models.IntegerField(choices=[(1, 'Micro - 3 - mini frames'), (2, 'Little - queen castle or nuc'), (3, 'Small - single storey brood chamber, 9-10 frames'), (4, 'Large - double storey brood chamber, 18 - 20 frames'), (5, 'Huge - 3 or more storey brood chamber')], default=3, help_text='Size of the colony'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='numbers',
            field=models.IntegerField(choices=[(0, 'Not recorded'), (5, 'Not enough')], default=0, help_text='How many bees in the hive (seams of bees)?'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='varroa',
            field=models.IntegerField(choices=[(0, 'Not recorded'), (1, 'No varroa seen'), (2, '1 - 2 varroa / 300 bees'), (3, '3 - 6 varroa / 300 bees'), (4, '7 - 15 varroa / 300 bees'), (5, 'More than 15 varroa / 300 bees')], default=0, help_text='How much varroa is in the hive?'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='weight',
            field=models.IntegerField(choices=[(0, 'Not recorded'), (5, 'No stores')], default=0, help_text='How heavy is the hive?'),
        ),
    ]
