# Generated by Django 3.2.6 on 2022-04-08 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beedb', '0049_merge_20220326_1537'),
        ('beedb', '0056_auto_20220408_1336'),
    ]

    operations = [
    ]
