# Generated by Django 4.1.2 on 2022-10-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beedb", "0059_rename_treatment_treatment_treatmenttype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treatment",
            name="insertDt",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date treatment put in"
            ),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="postVarroa",
            field=models.IntegerField(
                choices=[
                    (0, "Not recorded"),
                    (1, "No varroa seen"),
                    (2, "1 - 2 varroa / 300 bees"),
                    (3, "3 - 6 varroa / 300 bees"),
                    (4, "7 - 15 varroa / 300 bees"),
                    (5, "More than 15 varroa / 300 bees"),
                ],
                default=0,
                help_text="How much varroa is in the hive after treating?",
                verbose_name="Varroa count after treatment",
            ),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="preVarroa",
            field=models.IntegerField(
                choices=[
                    (0, "Not recorded"),
                    (1, "No varroa seen"),
                    (2, "1 - 2 varroa / 300 bees"),
                    (3, "3 - 6 varroa / 300 bees"),
                    (4, "7 - 15 varroa / 300 bees"),
                    (5, "More than 15 varroa / 300 bees"),
                ],
                default=0,
                help_text="How much varroa is in the hive before treating?",
                verbose_name="Varroa count before treatment",
            ),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="removeDt",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date treatment to be removed"
            ),
        ),
    ]
