# Generated by Django 4.1.2 on 2022-10-31 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beedb', '0062_remove_inspection_adddiary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatment',
            old_name='notes',
            new_name='trNotes',
        ),
    ]
