# Generated by Django 4.1.6 on 2023-02-14 22:01

import beedb.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("beedb", "0066_alter_apiary_latitude_alter_apiary_longitude_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Picture",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("img", models.ImageField(upload_to=beedb.models.user_directory)),
                ("uploadDt", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "apiary",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="beedb.apiary",
                    ),
                ),
                (
                    "beek",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "colony",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="beedb.colony",
                    ),
                ),
                (
                    "inspection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="beedb.inspection",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploadDt"],
            },
        ),
        migrations.AlterField(
            model_name="diary",
            name="dueDt",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 2, 21, 22, 1, 47, 686525, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date to complete by",
            ),
        ),
        migrations.DeleteModel(
            name="Image",
        ),
    ]
