# Generated by Django 3.1.2 on 2020-12-04 23:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('beedb', '0009_auto_20201205_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='dt',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
