# Generated by Django 3.2.6 on 2021-08-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beedb', '0035_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
