# Generated by Django 3.2.7 on 2021-12-05 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beedb', '0036_message_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='colony1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='beedb.colony'),
        ),
    ]
