# Generated by Django 3.2.6 on 2022-03-23 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beedb', '0044_alter_diary_duedt'),
        ('beedb', '0045_alter_feedback_status'),
    ]

    operations = [
    ]
