# Generated by Django 3.2.6 on 2022-03-24 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beedb', '0046_merge_20220323_1453'),
        ('beedb', '0046_treatment_treatmenttype'),
    ]

    operations = [
    ]
