# Generated by Django 3.2.7 on 2022-04-02 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beedb', '0051_auto_20220402_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sizechoice',
            options={'ordering': ['value']},
        ),
    ]
