# Generated by Django 3.2.7 on 2022-04-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beedb', '0056_auto_20220408_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='numbers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
