#Trigger this flow on a push
on: 
  push:
    branches:
      - '!master'
  workflow_dispatch:

# What to do
jobs:
  # Needs at least one job
    
  build-web:
    name: Build the docker web image
    # Runs-on defines the environment that the action runs on
    runs-on: ubuntu-latest
    # Get a postgreas database for testing
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
        # Each job can have one or more steps
    - name: Checkout
        # need to checkout the code so we can work on it
      uses: actions/checkout@v4
    - name: Setup python env
        # Need a python environment to work with
      uses: actions/setup-python@v5
    - name: Install req
        # Install things we need, e.g. docker
      run: pip install --quiet --requirement requirements.txt

    - name: List files
      run: ls -R

    - name: Run Django tests
      env:
        #DATABASE_URL: postgres://test_user:test_password@localhost:5432/test_db
        POSTGRES_HOST: postgres
        POSTGRES_NAME: test_db
        POSTGRES_USER: test_user
        POSTGRES_PASSWORD: test_password
        POSTGRES_PORT: 5432

      run: |
        cd bee
        python manage.py migrate
        python manage.py test

    -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
    -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
    -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
            context: .
            # platforms: linux/amd64,linux/arm64,linux/arm/v7 
            push: true
            tags: jimboeri/bee-db-web:dev

  build-background:
    name: Build the docker background image
    # Runs-on defines the environment that the action runs on
    runs-on: ubuntu-latest
    steps:
        # Each job can have one or more steps
    - name: Checkout
        # need to checkout the code so we can work on it
      uses: actions/checkout@v4
    - name: Setup python env
        # Need a python environment to work with
      uses: actions/setup-python@v5
    - name: Install req
        # Install things we need, e.g. docker
      run: pip install --quiet --requirement background-requirements.txt

    -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
    -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
    -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
            context: .
            file: script-dockerfile
            # platforms: linux/amd64,linux/arm64,linux/arm/v7 
            push: true
            tags: jimboeri/bee-db-background:dev
